In [9]:
import pandas as pd

df=pd.read_csv('./data/sales.csv')

# 2. 数据排序
# 2.1 根据销售数量 倒序排序
df.sort_values('销售数量',ascending=False)

# 2.2 根据 单价 升序排序
df.sort_values('单价')

# 2.3 根据 单价 升序排序，价格一样，再根据 销售数量 降序排序
df.sort_values(['单价','销售数量'],ascending=[True,False])
#df.sort_values(['单价','销售数量'],ascending=True) #如果都是升序，可以直接一个True

          订单号  产品类型           产品名称  销售数量       单价 客户所在城市  支付方式        订单日期
82   NO000083  美妆个护         云南白药牙膏     5    26.99     青岛   支付宝  2025-10-29
129  NO000130  美妆个护         云南白药牙膏    12    28.62     长沙  微信支付  2026-03-08
64   NO000065  美妆个护         云南白药牙膏    12    30.40     广州   支付宝  2025-08-31
31   NO000032  美妆个护         云南白药牙膏    19    31.13     南京  货到付款  2025-04-24
47   NO000048  美妆个护         云南白药牙膏    12    31.53     青岛   银行卡  2025-06-27
..        ...   ...            ...   ...      ...    ...   ...         ...
84   NO000085  数码3C  iPhone 16 Pro    20  7882.86     长沙   支付宝  2025-11-08
112  NO000113  数码3C  iPhone 16 Pro     7  7906.70     长沙   支付宝  2026-01-10
187  NO000188  数码3C  iPhone 16 Pro    13  8218.56     成都   银行卡  2026-08-15
89   NO000090  数码3C  iPhone 16 Pro    18  8270.65     上海   银行卡  2025-11-15
38   NO000039  数码3C  iPhone 16 Pro     6  8323.95     重庆   信用卡  2025-05-23

[200 rows x 8 columns]

In [ ]:
df= pd.read_csv('data/sales.csv',nrows=30)


#3.分组
#3.1 根据 产品类型 分组，统计各个类型的 订单数量 - count
# 所选列如果有缺失值，会被过滤掉
df.groupby('产品类型')['订单号'].count() 

#3.2 根据 产品类型 分组，统计各个类型的 销售之和 - sum
df.groupby('产品类型')['销售数量'].sum()

#3.3 根据 产品类型 分组，统计各个类型的 销售金额 - sum
df['销售金额']=df['销售数量']*df['单价']
#df
df.groupby('产品类型')['销售金额'].sum()

#3.4 根据 产品类型 分组，统计各个类型的最低商品价格 - min
df.groupby('产品类型')['单价'].min()

#3.5 根据 产品类型 分组，统计各个类型的最高商品价格 - max
df.groupby('产品类型')['单价'].max()

#3.6 根据 产品类型 分组，统计各个类型的平均商品价格 - mean
df.groupby('产品类型')['单价'].mean().round(2)

#3.7 根据 产品类型 分组，统计各个类别的商品的 平均单价，最高单价，最低单价
df.groupby('产品类型')['单价'].agg(['mean','max','min'])

#3.8 根据 产品类型 分组，统计各个类型的 销售数量 之和，销售金额 之和，平均 单价
# 平均单价 保留2位小数
df.groupby('产品类型').agg({'销售数量':'sum','销售金额':'sum','单价':'mean'}).round(2) #或.routd({'单价':2})指定列保留两位小数

      销售数量     销售金额      单价
产品类型
图书音像    27   2892.8    97.5
家用电器    37  43722.9  1766.3
数码3C     9  43221.1  3655.8
服饰鞋包    34  22273.3   561.7
美妆个护    38  19452.2   397.5
运动户外    32   8922.4   283.3
食品生鲜    51  10894.6   234.7